Traceback (most recent call last):
  File "/home/dokhanhnam1199/QD/problems/cvrp_aco/eval.py", line 11, in <module>
    import gpt
  File "/home/dokhanhnam1199/QD/problems/cvrp_aco/gpt.py", line 1, in <module>
    def heuristics_v2(distance_matrix: np.ndarray, coordinates: np.ndarray, demands: np.ndarray, capacity: int,
NameError: name 'np' is not defined
Traceback (most recent call last):
  File "/home/dokhanhnam1199/QD/problems/cvrp_aco/SLOC.py", line 7, in <module>
    import gpt
  File "/home/dokhanhnam1199/QD/problems/cvrp_aco/gpt.py", line 1, in <module>
    def heuristics_v2(distance_matrix: np.ndarray, coordinates: np.ndarray, demands: np.ndarray, capacity: int,
NameError: name 'np' is not defined
Traceback (most recent call last):
  File "/home/dokhanhnam1199/QD/problems/cvrp_aco/cyclomatic_complexity.py", line 7, in <module>
    import gpt
  File "/home/dokhanhnam1199/QD/problems/cvrp_aco/gpt.py", line 1, in <module>
    def heuristics_v2(distance_matrix: np.ndarray, coordinates: np.ndarray, demands: np.ndarray, capacity: int,
NameError: name 'np' is not defined
Traceback (most recent call last):
  File "/home/dokhanhnam1199/QD/problems/cvrp_aco/halstead.py", line 7, in <module>
    import gpt
  File "/home/dokhanhnam1199/QD/problems/cvrp_aco/gpt.py", line 1, in <module>
    def heuristics_v2(distance_matrix: np.ndarray, coordinates: np.ndarray, demands: np.ndarray, capacity: int,
NameError: name 'np' is not defined
