[*] Running ...
/home/dokhanhnam1199/QD/problems/bpp_online/gpt.py:30: RuntimeWarning: invalid value encountered in divide
  z_fit = (1.0 / (leftover + 1e-9) - np.mean(fit_quality)) / (np.std(fit_quality) + 1e-9)
/home/dokhanhnam1199/QD/problems/bpp_online/gpt.py:46: RuntimeWarning: invalid value encountered in divide
  # Global statistics before any placement
/home/dokhanhnam1199/.local/lib/python3.10/site-packages/numpy/_core/numeric.py:442: RuntimeWarning: invalid value encountered in cast
  multiarray.copyto(res, fill_value, casting='unsafe')
/home/dokhanhnam1199/QD/problems/bpp_online/gpt.py:59: RuntimeWarning: invalid value encountered in cast
  normalized_entropy = system_sensitivity / (entropy_std + 1e-9)
Traceback (most recent call last):
  File "/home/dokhanhnam1199/QD/problems/bpp_online/eval.py", line 112, in <module>
    avg_num_bins = -evaluate(dataset)
  File "/home/dokhanhnam1199/QD/problems/bpp_online/eval.py", line 55, in evaluate
    _, bins_packed = online_binpack(items.astype(float), bins)
  File "/home/dokhanhnam1199/QD/problems/bpp_online/eval.py", line 28, in online_binpack
    priorities = priority(item, bins[valid_bin_indices])
  File "/home/dokhanhnam1199/QD/problems/bpp_online/gpt.py", line 30, in priority_v2
    z_fit = (1.0 / (leftover + 1e-9) - np.mean(fit_quality)) / (np.std(fit_quality) + 1e-9)
IndexError: boolean index did not match indexed array along axis 0; size of axis is 4987 but size of corresponding boolean axis is 4988
53
4
