[*] Running ...
[*] Dataset loaded: C:\Users\Nam\Documents\GitHub\HSEvo/problems/tsp_aco\dataset\train50_dataset.npy with 5 instances.
Traceback (most recent call last):
  File "C:\Users\Nam\Documents\GitHub\HSEvo/problems/tsp_aco/eval.py", line 53, in <module>
    obj = solve(node_pos)
  File "C:\Users\Nam\Documents\GitHub\HSEvo/problems/tsp_aco/eval.py", line 26, in solve
    heu = heuristics(dist_mat.copy()) + 1e-9
          ~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\Nam\Documents\GitHub\HSEvo\problems\tsp_aco\gpt.py", line 45, in heuristics_v2
    tours[i][idx1], tours[i][idx2] = tours[i][idx2], tours[i][idx1]
                                              ^^^^
UnboundLocalError: cannot access local variable 'idx2' where it is not associated with a value
