[*] Running ...
[*] Dataset loaded: C:\Users\Nam\Documents\GitHub\HSEvo/problems/tsp_aco\dataset\train50_dataset.npy with 5 instances.
Traceback (most recent call last):
  File "C:\Users\Nam\Documents\GitHub\HSEvo/problems/tsp_aco/eval.py", line 53, in <module>
    obj = solve(node_pos)
  File "C:\Users\Nam\Documents\GitHub\HSEvo/problems/tsp_aco/eval.py", line 26, in solve
    heu = heuristics(dist_mat.copy()) + 1e-9
          ~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\Nam\Documents\GitHub\HSEvo\problems\tsp_aco\gpt.py", line 48, in heuristics_v2
ValueError: shape mismatch: value array of shape (49,) could not be broadcast to indexing result of shape (50,)
