[*] Running ...
[*] Dataset loaded: /home/dokhanhnam1199/QD/problems/cvrp_aco/dataset/train50_dataset.npy with 10 instances.
Traceback (most recent call last):
  File "/home/dokhanhnam1199/QD/problems/cvrp_aco/eval.py", line 60, in <module>
    obj = solve(node_pos, demand)
  File "/home/dokhanhnam1199/QD/problems/cvrp_aco/eval.py", line 28, in solve
    heu = heuristics(dist_mat.copy(), node_pos.copy(), demand.copy(), CAPACITY) + 1e-9
  File "/home/dokhanhnam1199/QD/problems/cvrp_aco/gpt.py", line 63, in heuristics_v2
  File "/home/dokhanhnam1199/QD/problems/cvrp_aco/gpt.py", line 63, in <listcomp>
  File "/home/dokhanhnam1199/QD/problems/cvrp_aco/gpt.py", line 38, in calculate_fitness
    remaining_nodes.remove(next_node)
TypeError: object of type 'int' has no len()
88
7
358.13347381033844
